name: Deploy Subgraph

on:
  workflow_dispatch:
    inputs:
      subgraph:
        type: choice
        description: Select subgraph
        options:
          - harvesters
          - wastelands

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./subgraphs/${{ inputs.subgraph }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Setup environment
        uses: Firenza/secrets-to-env@v1.2.0
        with:
            secrets: ${{ toJSON(secrets) }}

      - name: Prepare
        run: yarn prepare

      - name: Generate
        run: yarn codegen

      - name: Create
        run: yarn graph create --node $GRAPH_NODE_ENDPOINT ${{ inputs.subgraph }}-pending

      - name: Deploy
        run: yarn graph deploy ${{ inputs.subgraph }}-pending --ipfs $GRAPH_IPFS_ENDPOINT --node $GRAPH_NODE_ENDPOINT --version-label v0.0.0
