name: Deploy Subgraph

run-name: Deploy ${{ inputs.subgraph }} Subgraph

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select environment
        type: environment
        required: true 
      subgraph:
        type: choice
        description: Select subgraph
        required: true
        options:
          - harvesters
          - legions
          - magic
          - meem
          - smol-bodies
          - smol-domains
          - treasure-fragments
          - treasure-tags
          - wastelands

jobs:
  deploy:
    name: Deploy ${{ inputs.subgraph }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./subgraphs/${{ inputs.subgraph }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Setup environment
        uses: Firenza/secrets-to-env@v1.2.0
        with:
            secrets: ${{ toJSON(secrets) }}

      - name: Prepare
        run: yarn prepare

      - name: Generate
        run: yarn codegen

      - name: Create
        run: yarn graph create --node $GRAPH_NODE_ENDPOINT ${{ inputs.subgraph }}-pending

      - name: Deploy Pending
        if: inputs.environment == 'Development'
        run: yarn graph deploy ${{ inputs.subgraph }}-pending --ipfs $GRAPH_IPFS_ENDPOINT --node $GRAPH_NODE_ENDPOINT --version-label v0.0.0

      - name: Deploy
        if: inputs.environment == 'Production'
        run: yarn graph deploy ${{ inputs.subgraph }} --ipfs $GRAPH_IPFS_ENDPOINT --node $GRAPH_NODE_ENDPOINT --version-label v0.0.0
  remove:
    name: Remove pending ${{ inputs.subgraph }}
    if: inputs.environment == 'Production'
    needs: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./subgraphs/${{ inputs.subgraph }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Setup environment
        uses: Firenza/secrets-to-env@v1.2.0
        with:
            secrets: ${{ toJSON(secrets) }}

      - name: Remove
        run: yarn graph remove --node $GRAPH_NODE_ENDPOINT ${{ inputs.subgraph }}-pending
